version: "3.7"
services:
  plastrond:
    image: docker.lib.umd.edu/plastrond
    environment:
      - JWT_SECRET
    configs:
      - source: plastrond
        target: /etc/plastrond.yml
      - source: archelon_id
        target: /etc/plastron/auth/archelon_id
        mode: 0400
    volumes:
      - plastrond:/var/opt/plastron
configs:
  archelon_id:
    # Private key for archelon SFTP
    # The corresponding public key should be added to Archelon
    file: ./plastron/archelon_id
  plastrond:
    file: ./plastron/plastron.yml
volumes:
  plastrond:
